### ISSUE TITLE
Usage without a module?

### ISSUE THREAD

**Issue by sgpascoe** [words/n-gram#10]
I'm trying to use `const { bigram, trigram, nGram } = require('n-gram');`

but I'm getting the error 

`Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\x\x\x\x\node_modules\n-gram\index.js from C:\Users\x\x\x\x\server.js not supported.
Instead change the require of index.js in C:\Users\x\x\x\x\server.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\Users\x\x\x\x\server.js:8:36) {
  code: 'ERR_REQUIRE_ESM'`

**Comment by wooorm** [comment]
This package is [ESM only](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).
